# Generated by Django 4.2.4 on 2023-08-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='name',
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_name',
            field=models.CharField(default='todo', max_length=300),
            preserve_default=False,
        ),
    ]
