# Generated by Django 4.2.4 on 2023-08-24 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_todo_name_todo_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='name',
            new_name='todo_name',
        ),
    ]
